sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - vendor
    - zf-mkdoc-theme

env:
  global:
    - SITE_URL: https://weierophinney.github.io/zf-docs-toolchain-experiment
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/weierophinney/zf-docs-toolchain-experiment.git
    - secure: "FI3tgH7aRpHK4hPrld+hRCvVO29xmelGHrUbriUDWya1fPKB8S/E1QT6Ayl26i/l2qo+XDUKokbRd8PavH5A0YW76gv5s+OB5RErZ+1SBNAGAAkQLX/6F5mRMXHBQcx11IvD3VL5CxpASigNjZtXFT2z5mn7rWHKLey8UGZ5GOB6p+pNbsSVRvTETClfN7HaJvvjawg0B9qk5+DNu9KVeb6Vb5YWz9xAO6Tz9gihXmMz8ijQ0hL+M2wXPBPA5okeOwPoX3c4WPJsOGsUQK37ZlS5M6505/xuHChz4kZJa2/XSgYDIVwUrNhA7B+/jhQNRa9AhigfRs0Y+eL9vuiaWJg4U7yy9pJ3/HaDclCVMxPauMdZYFOm6kRF6EeumTZckmefjoZDKmfCgzyD1AJVFDRwkoAoc4q3A6qMws7okX3rLN3NbmikDUZu/BfunFBnjeCXi2hW2cWN5pNp4ak/ZCLfPrOvvBBUhvnTHI+dLvT4PhSl8zxLJQW+JBHvfklWMEnhYRkGVvCnUpQna7r6M9qp13Od6ZyJYm1P3BxWgRWJvVerdA1q7u2wbJiK3yxCZxhyYfWCMEAT72/uEPlxHDP51D95G+xTDtYcvZyZ6aoa0kZ62iUjZJ7F0SVa7pjzFJ0R/2aKCkSM3Ez0lrJvRVky40N1HbY8YVtewgI5YpE="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - DEPLOY_DOCS=true
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - export PATH="$HOME/.local/bin:$PATH"
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls:dev-master ; fi

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer test-coverage ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then composer test ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer coveralls ; fi

after_success:
  - if [[ $DEPLOY_DOCS == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then pip install --user mkdocs ; fi
  - if [[ $DEPLOY_DOCS == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then pip install --user pymdown-extensions ; fi
  - if [[ $DEPLOY_DOCS == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && ! -d "zf-mkdoc-theme" ]]; then $(curl -s -L https://github.com/weierophinney/zf-mkdoc-theme/releases/latest | egrep -o '/weierophinney/zf-mkdoc-theme/archive/[0-9]*\.[0-9]*\.[0-9]*.tar.gz' | head -n1 | wget -O zf-mkdoc-theme.tgz --base=https://github.com/ -i - && mkdir zf-mkdoc-theme && $(cd zf-mkdoc-theme && tar xzf ../zf-mkdoc-theme.tgz --strip-components=1)) ; fi
  - if [[ $DEPLOY_DOCS == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && -f "zf-mkdoc-theme/deploy.sh"  ]]; then ./zf-mkdoc-theme/deploy.sh ; fi

notifications:
  email: true
